### ISSUE TITLE
boot.bin with no bitstream: INVALID_HEADER_FAIL 

### ISSUE THREAD

**Issue by igaw** [antmicro/zynq-mkbootimage#2]
I'd like to generate a boot.bin without a bitstream in it:

```
the_ROM_image:
{
	[bootloader]fsbl.elf
	HelloWorld.elf
}
```
As it turns out FSBL is not happy with the generated image:

```
Xilinx First Stage Boot Loader 
Release 2016.4  Mar 21 2017-12:58:25
Devcfg driver initialized 
Silicon Version 3.1
Watchdog driver initialized 
Boot mode is SD
SD: rc= 0
SD Init Done 
Flash Base Address: 0xE0100000
Reboot status register: 0x60400000
Multiboot Register: 0x0000C000
Image Start Address: 0x00000000
Partition Header Offset:0x00000C80
Partition Count: 3
Partition Number: 1
Header Dump
Image Word Len: 0x00002002
Data Word Len: 0x00002002
Partition Word Len:0x00002002
Load Addr: 0x00100000
Exec Addr: 0x00100000
Partition Start: 0x000095D0
Partition Attr: 0x00000010
Partition Checksum Offset: 0x00000000
Section Count: 0x00000001
Checksum: 0xFFDF07C8
Application
Partition Number: 2
Header Dump
Image Word Len: 0x00000000
Data Word Len: 0x00000000
Partition Word Len:0x00000000
Load Addr: 0x00000000
Exec Addr: 0x00000000
Partition Start: 0x00000000
Partition Attr: 0x00000000
Partition Checksum Offset: 0x00000000
Section Count: 0x00000000
Checksum: 0x00000000
IMAGE_HAS_NO_PARTITIONS
INVALID_HEADER_FAIL
FSBL Status = 0xA00D

This Boot Mode Doesn't Support Fallback
In FsblHookFallback function 
```

This is for a ZYNQ 7000 device.

**Comment by tgorochowik** [comment]
Hello Daniel, thanks for the report. We will take a look at it in spare time.

**Comment by igaw** [comment]
Hi Tomasz, if it helps I can send you the input files privately. I can't post them publicly :)

**Comment by tgorochowik** [comment]
Hello Daniel, sure, that would be very helpful! Please send the files to tgorochowik@antmicro.com

**Comment by tgorochowik** [comment]
Hello again, thanks for the files!
It turns out that some versions of fsbl 'guess' the partition count in boot.bin based on the end offset of the partition headers. We fixed the calculation of that offset and now your files run the same both with mkbootimage and the original bootgen.
Please let us know if you have any extra questions/remarks.
Cheers, Tom

**Comment by igaw** [comment]
Many thanks for looking at it. I tried the current head and there is a change in the output but u-boot (it is the same with the demo app I sent you privately) is still not started. It just stops there and nothing is printed anymore after that.

```
Xilinx First Stage Boot Loader 
Release 2016.4  Mar 21 2017-12:58:25
Devcfg driver initialized 
Silicon Version 3.1
Watchdog driver initialized 
Boot mode is SD
SD: rc= 0
SD Init Done 
Flash Base Address: 0xE0100000
Reboot status register: 0x60400000
Multiboot Register: 0x0000C000
Image Start Address: 0x00000000
Partition Header Offset:0x00000C80
Partition Count: 2
Partition Number: 1
Header Dump
Image Word Len: 0x0001E576
Data Word Len: 0x0001E576
Partition Word Len:0x0001E576
Load Addr: 0x04000000
Exec Addr: 0x04000000
Partition Start: 0x000095D0
Partition Attr: 0x00000010
Partition Checksum Offset: 0x00000000
Section Count: 0x00000001
Checksum: 0xF7F9B76C
Application
Handoff Address: 0x04000000
RTC not found
```

If the bitstream is part of the image the output looks like this:

```
Xilinx First Stage Boot Loader 
Release 2016.4  Mar 21 2017-12:58:25
Devcfg driver initialized 
Silicon Version 3.1
Watchdog driver initialized 
Boot mode is SD
SD: rc= 0
SD Init Done 
Flash Base Address: 0xE0100000
Reboot status register: 0x60400000
Multiboot Register: 0x0000C000
Image Start Address: 0x00000000
Partition Header Offset:0x00000C80
Partition Count: 3
Partition Number: 1
Header Dump
Image Word Len: 0x0016CFC4
Data Word Len: 0x0016CFC4
Partition Word Len:0x0016CFC4
Load Addr: 0x00000000
Exec Addr: 0x00000000
Partition Start: 0x000095D0
Partition Attr: 0x00000020
Partition Checksum Offset: 0x00000000
Section Count: 0x00000001
Checksum: 0xFFBAF872
Bitstream
In FsblHookBeforeBitstreamDload function 
PCAP:StatusReg = 0x40000A30
PCAP:device ready
PCAP:Clear done
Level Shifter Value = 0xA 
Devcfg Status register = 0x40000A30 
PCAP:Fabric is Initialized done
PCAP register dump:
PCAP CTRL 0xF8007000: 0x4C00E07F
PCAP LOCK 0xF8007004: 0x0000001A
PCAP CONFIG 0xF8007008: 0x00000508
PCAP ISR 0xF800700C: 0x0802000B
PCAP IMR 0xF8007010: 0xFFFFFFFF
PCAP STATUS 0xF8007014: 0x00003A30
PCAP DMA SRC ADDR 0xF8007018: 0x00100001
PCAP DMA DEST ADDR 0xF800701C: 0xFFFFFFFF
PCAP DMA SRC LEN 0xF8007020: 0x0016CFC4
PCAP DMA DEST LEN 0xF8007024: 0x0016CFC4
PCAP ROM SHADOW CTRL 0xF8007028: 0xFFFFFFFF
PCAP MBOOT 0xF800702C: 0x0000C000
PCAP SW ID 0xF8007030: 0x00000000
PCAP UNLOCK 0xF8007034: 0x757BDF0D
PCAP MCTRL 0xF8007080: 0x30800100

DMA Done ! 

FPGA Done ! 
In FsblHookAfterBitstreamDload function 
Partition Number: 2
Header Dump
Image Word Len: 0x0001E576
Data Word Len: 0x0001E576
Partition Word Len:0x0001E576
Load Addr: 0x04000000
Exec Addr: 0x04000000
Partition Start: 0x001765A0
Partition Attr: 0x00000010
Partition Checksum Offset: 0x00000000
Section Count: 0x00000001
Checksum: 0xF7E2E78C
Application
Handoff Address: 0x04000000
RTC configured
MAC address configured successfully from EEPROM
Detected KSZ9031 Ethernet PHY
PHY configured
SUCCESSFUL_HANDOFF
FSBL Status = 0x1


U-Boot 2016.01-00075-gc63752e (Mar 21 2017 - 14:36:51 +0100)

Model: Enclustra Mercury family SOM's
Board: Xilinx Zynq
I2C:   ready
DRAM:  ECC disabled 1 GiB
NAND:  512 MiB
MMC:   sdhci@e0100000: 0
```

**Comment by igaw** [comment]
Ahhhh, maybe I need an updated FSBL which does some more initializing. I check with our hardware guys.

**Comment by tgorochowik** [comment]
Hello,
this time the problem is no longer caused by a faulty image, but by a fail in your application. The application ends exactly the same if you use the original bootgen for this.

As you can see in the log it hangs after trying to configure RTC. It is possible that it is trying to to talk via i2c which should be routed through fpga. Zynqs tend to hang if they try to write something on addresses that are not mapped to a valid device (like a missing i2c controller).

You could try disabling all the i2c devices (see the patches you probably applied to your FSBL).

Best, Tom

**Comment by igaw** [comment]
Hi Tom,

This very likely the problem now. So I would say this bug is fixed.

Excellent work!
Daniel

**Comment by igaw** [comment]
Just to confirm. With a patched FSBL which doesn't try to access I2C devices, u-boot is showing up.
